@baseURl = http://localhost:3000/api

# @name get goals
GET {{baseURl}}/goals HTTP/1.1
Content-Type: application/json

###

PUT {{baseURl}}/goals/630cd45f348c4d6d5f8d0ae4 HTTP/1.1
Content-Type: application/json

{
    "text": "Updated goal"
}

###

POST {{baseURl}}/goals HTTP/1.1
Content-Type: application/json

{
    "text": "My Second Goal"
}

###

DELETE  {{baseURl}}/goals/630cd45f348c4d6d5f8d0ae4 HTTP/1.1
Content-Type: application/json