@baseURl = http://localhost:3000/api

# @name get goals
GET {{baseURl}}/goals HTTP/1.1
Content-Type: application/json

###

PUT {{baseURl}}/goals/1 HTTP/1.1
Content-Type: application/json

###

POST {{baseURl}}/goals HTTP/1.1
Content-Type: application/json

###

DELETE  {{baseURl}}/goals/1 HTTP/1.1
Content-Type: application/json